version: "3.9"
services:
  db:
    image: postgres
    container_name: pg_db
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=library_db
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    
volumes:
  pg_data: